[package]
name = "rust-cli-buddy"
version = "0.1.0"
edition = "2021"
authors = ["Jesse jesse.greenough84@gmail.com"]
license = "MIT"
default-run = "buddy-manager"

[workspace]
members = [
    "buddy-manager",
    "calculator",
    "password-manager",
    "password-generator",
    "file-organizer",
    "task-manager",
    "development-timer",
    "word-analyzer",
]

[dependencies]
buddy-utils = { path = "./buddy-utils" }
chrono = "0.4"
dotenv = "0.16.0"
rand = "0.8.4"
regex = "1"
reqwest = { version = "0.11.5", features = ["blocking", "json"] }
rusqlite = "0.25.0"
serde = { version = "1.0", features = ["derive"] }
termion = "1.5.6"
time = "0.2"


[[bin]]
name = "ai-assistant"
path = "ai-assistant/src/main.rs"

[[bin]]
name = "buddy-manager"
path = "buddy-manager/src/main.rs"

[[bin]]
name = "buddy-utils"
path = "buddy-utils/src/lib.rs"

[[bin]]
name = "calculator"
path = "calculator/src/main.rs"

[[bin]]
name = "development-timer"
path = "development-timer/src/main.rs"

[[bin]]
name = "file-organizer"
path = "file-organizer/src/main.rs"

[[bin]]
name = "password-generator"
path = "password-generator/src/main.rs"

[[bin]]
name = "password-manager"
path = "password-manager/src/main.rs"

[[bin]]
name = "task-manager"
path = "task-manager/src/main.rs"

[[bin]]
name = "word-analyzer"
path = "word-analyzer/src/main.rs"