[package]
name = "word-analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buddy_service = { path = "../buddy_service" }


[[bin]]
name = "word-analyzer"
path = "src/main.rs"